package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_area_info
 * @Data 2017-12-28
 * @Author chanin 
 * 行政区域信息
 */
public class AreaInfo extends BasicObject implements Serializable {
    // 区域主键 (主健ID)
    private String areaId;

    // 父级主键(可选项)
    private String prevId;

    // 区域编号(必填项)
    private String areaCode;

    // 区域名称(必填项)
    private String areaName;

    // 区域类型(必填项)
    private String areaType;

    // 区域首拼(必填项)
    private String areaPiny;

    // 区域层级(必填项)
    private Integer areaRank;

    // 区域排序(必填项)
    private Integer areaSort;

    // 子集标志(必填项)
    private String subsetSymbol;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;
    
    //------------------------
  	//业务逻辑使用属性
  	//------------------------
    private String fullName; //区域全名
    private AreaInfo prevArea; //父级区域

    private static final long serialVersionUID = 1L;

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    public String getPrevId() {
        return prevId;
    }

    public void setPrevId(String prevId) {
        this.prevId = prevId == null ? null : prevId.trim();
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    public String getAreaType() {
        return areaType;
    }

    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    public String getAreaPiny() {
        return areaPiny;
    }

    public void setAreaPiny(String areaPiny) {
        this.areaPiny = areaPiny == null ? null : areaPiny.trim();
    }

    public Integer getAreaRank() {
        return areaRank;
    }

    public void setAreaRank(Integer areaRank) {
        this.areaRank = areaRank;
    }

    public Integer getAreaSort() {
        return areaSort;
    }

    public void setAreaSort(Integer areaSort) {
        this.areaSort = areaSort;
    }

    public String getSubsetSymbol() {
        return subsetSymbol;
    }

    public void setSubsetSymbol(String subsetSymbol) {
        this.subsetSymbol = subsetSymbol == null ? null : subsetSymbol.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }
    
    

    public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public AreaInfo getPrevArea() {
		return prevArea;
	}

	public void setPrevArea(AreaInfo prevArea) {
		this.prevArea = prevArea;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_area_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static AreaInfo.Builder builder() {
        return new AreaInfo.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", areaId=").append(areaId);
        sb.append(", prevId=").append(prevId);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", areaName=").append(areaName);
        sb.append(", areaType=").append(areaType);
        sb.append(", areaPiny=").append(areaPiny);
        sb.append(", areaRank=").append(areaRank);
        sb.append(", areaSort=").append(areaSort);
        sb.append(", subsetSymbol=").append(subsetSymbol);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AreaInfo other = (AreaInfo) that;
        return (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
            && (this.getPrevId() == null ? other.getPrevId() == null : this.getPrevId().equals(other.getPrevId()))
            && (this.getAreaCode() == null ? other.getAreaCode() == null : this.getAreaCode().equals(other.getAreaCode()))
            && (this.getAreaName() == null ? other.getAreaName() == null : this.getAreaName().equals(other.getAreaName()))
            && (this.getAreaType() == null ? other.getAreaType() == null : this.getAreaType().equals(other.getAreaType()))
            && (this.getAreaPiny() == null ? other.getAreaPiny() == null : this.getAreaPiny().equals(other.getAreaPiny()))
            && (this.getAreaRank() == null ? other.getAreaRank() == null : this.getAreaRank().equals(other.getAreaRank()))
            && (this.getAreaSort() == null ? other.getAreaSort() == null : this.getAreaSort().equals(other.getAreaSort()))
            && (this.getSubsetSymbol() == null ? other.getSubsetSymbol() == null : this.getSubsetSymbol().equals(other.getSubsetSymbol()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getPrevId() == null) ? 0 : getPrevId().hashCode());
        result = prime * result + ((getAreaCode() == null) ? 0 : getAreaCode().hashCode());
        result = prime * result + ((getAreaName() == null) ? 0 : getAreaName().hashCode());
        result = prime * result + ((getAreaType() == null) ? 0 : getAreaType().hashCode());
        result = prime * result + ((getAreaPiny() == null) ? 0 : getAreaPiny().hashCode());
        result = prime * result + ((getAreaRank() == null) ? 0 : getAreaRank().hashCode());
        result = prime * result + ((getAreaSort() == null) ? 0 : getAreaSort().hashCode());
        result = prime * result + ((getSubsetSymbol() == null) ? 0 : getSubsetSymbol().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_area_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_area_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private AreaInfo obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_area_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new AreaInfo();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.AREA_ID
         *
         * @param areaId the value for tb_area_info.AREA_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder areaId(String areaId) {
            obj.setAreaId(areaId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.PREV_ID
         *
         * @param prevId the value for tb_area_info.PREV_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder prevId(String prevId) {
            obj.setPrevId(prevId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.AREA_CODE
         *
         * @param areaCode the value for tb_area_info.AREA_CODE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder areaCode(String areaCode) {
            obj.setAreaCode(areaCode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.AREA_NAME
         *
         * @param areaName the value for tb_area_info.AREA_NAME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder areaName(String areaName) {
            obj.setAreaName(areaName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.AREA_TYPE
         *
         * @param areaType the value for tb_area_info.AREA_TYPE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder areaType(String areaType) {
            obj.setAreaType(areaType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.AREA_PINY
         *
         * @param areaPiny the value for tb_area_info.AREA_PINY
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder areaPiny(String areaPiny) {
            obj.setAreaPiny(areaPiny);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.AREA_RANK
         *
         * @param areaRank the value for tb_area_info.AREA_RANK
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder areaRank(Integer areaRank) {
            obj.setAreaRank(areaRank);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.AREA_SORT
         *
         * @param areaSort the value for tb_area_info.AREA_SORT
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder areaSort(Integer areaSort) {
            obj.setAreaSort(areaSort);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.SUBSET_SYMBOL
         *
         * @param subsetSymbol the value for tb_area_info.SUBSET_SYMBOL
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder subsetSymbol(String subsetSymbol) {
            obj.setSubsetSymbol(subsetSymbol);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_area_info.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_area_info.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.CREATE_TIME
         *
         * @param createTime the value for tb_area_info.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.CREATE_ID
         *
         * @param createId the value for tb_area_info.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.UPDATE_TIME
         *
         * @param updateTime the value for tb_area_info.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_area_info.UPDATE_ID
         *
         * @param updateId the value for tb_area_info.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_area_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public AreaInfo build() {
            return this.obj;
        }
    }
}