package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_bbxx
 * @Data 2017-12-28
 * @Author chanin 
 * 版本信息
 */
public class Bbxx extends BasicObject implements Serializable {
    // 版本主键 (主健ID)
    private String bbid;

    // 版本名称(可选项)
    private String bbmc;

    // 版本图标(可选项)
    private String bbtb;

    // 版本描述(必填项)
    private String bbms;

    // 版本平台：android、PC(可选项)
    private String bbpt;

    // 版本编号(必填项)
    private Integer bbbh;

    // 安装包名称(必填项)
    private String azbmc;

    // 版本地址(必填项)
    private String bbdz;

    // 发布时间(可选项)
    private String fbsj;

    // 强制更新(可选项)
    private String qzgx;

    // 下载次数(可选项)
    private Integer xzcs;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getBbid() {
        return bbid;
    }

    public void setBbid(String bbid) {
        this.bbid = bbid == null ? null : bbid.trim();
    }

    public String getBbmc() {
        return bbmc;
    }

    public void setBbmc(String bbmc) {
        this.bbmc = bbmc == null ? null : bbmc.trim();
    }

    public String getBbtb() {
        return bbtb;
    }

    public void setBbtb(String bbtb) {
        this.bbtb = bbtb == null ? null : bbtb.trim();
    }

    public String getBbms() {
        return bbms;
    }

    public void setBbms(String bbms) {
        this.bbms = bbms == null ? null : bbms.trim();
    }

    public String getBbpt() {
        return bbpt;
    }

    public void setBbpt(String bbpt) {
        this.bbpt = bbpt == null ? null : bbpt.trim();
    }

    public Integer getBbbh() {
        return bbbh;
    }

    public void setBbbh(Integer bbbh) {
        this.bbbh = bbbh;
    }

    public String getAzbmc() {
        return azbmc;
    }

    public void setAzbmc(String azbmc) {
        this.azbmc = azbmc == null ? null : azbmc.trim();
    }

    public String getBbdz() {
        return bbdz;
    }

    public void setBbdz(String bbdz) {
        this.bbdz = bbdz == null ? null : bbdz.trim();
    }

    public String getFbsj() {
        return fbsj;
    }

    public void setFbsj(String fbsj) {
        this.fbsj = fbsj == null ? null : fbsj.trim();
    }

    public String getQzgx() {
        return qzgx;
    }

    public void setQzgx(String qzgx) {
        this.qzgx = qzgx == null ? null : qzgx.trim();
    }

    public Integer getXzcs() {
        return xzcs;
    }

    public void setXzcs(Integer xzcs) {
        this.xzcs = xzcs;
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbxx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Bbxx.Builder builder() {
        return new Bbxx.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bbid=").append(bbid);
        sb.append(", bbmc=").append(bbmc);
        sb.append(", bbtb=").append(bbtb);
        sb.append(", bbms=").append(bbms);
        sb.append(", bbpt=").append(bbpt);
        sb.append(", bbbh=").append(bbbh);
        sb.append(", azbmc=").append(azbmc);
        sb.append(", bbdz=").append(bbdz);
        sb.append(", fbsj=").append(fbsj);
        sb.append(", qzgx=").append(qzgx);
        sb.append(", xzcs=").append(xzcs);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Bbxx other = (Bbxx) that;
        return (this.getBbid() == null ? other.getBbid() == null : this.getBbid().equals(other.getBbid()))
            && (this.getBbmc() == null ? other.getBbmc() == null : this.getBbmc().equals(other.getBbmc()))
            && (this.getBbtb() == null ? other.getBbtb() == null : this.getBbtb().equals(other.getBbtb()))
            && (this.getBbms() == null ? other.getBbms() == null : this.getBbms().equals(other.getBbms()))
            && (this.getBbpt() == null ? other.getBbpt() == null : this.getBbpt().equals(other.getBbpt()))
            && (this.getBbbh() == null ? other.getBbbh() == null : this.getBbbh().equals(other.getBbbh()))
            && (this.getAzbmc() == null ? other.getAzbmc() == null : this.getAzbmc().equals(other.getAzbmc()))
            && (this.getBbdz() == null ? other.getBbdz() == null : this.getBbdz().equals(other.getBbdz()))
            && (this.getFbsj() == null ? other.getFbsj() == null : this.getFbsj().equals(other.getFbsj()))
            && (this.getQzgx() == null ? other.getQzgx() == null : this.getQzgx().equals(other.getQzgx()))
            && (this.getXzcs() == null ? other.getXzcs() == null : this.getXzcs().equals(other.getXzcs()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBbid() == null) ? 0 : getBbid().hashCode());
        result = prime * result + ((getBbmc() == null) ? 0 : getBbmc().hashCode());
        result = prime * result + ((getBbtb() == null) ? 0 : getBbtb().hashCode());
        result = prime * result + ((getBbms() == null) ? 0 : getBbms().hashCode());
        result = prime * result + ((getBbpt() == null) ? 0 : getBbpt().hashCode());
        result = prime * result + ((getBbbh() == null) ? 0 : getBbbh().hashCode());
        result = prime * result + ((getAzbmc() == null) ? 0 : getAzbmc().hashCode());
        result = prime * result + ((getBbdz() == null) ? 0 : getBbdz().hashCode());
        result = prime * result + ((getFbsj() == null) ? 0 : getFbsj().hashCode());
        result = prime * result + ((getQzgx() == null) ? 0 : getQzgx().hashCode());
        result = prime * result + ((getXzcs() == null) ? 0 : getXzcs().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_bbxx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_bbxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Bbxx obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_bbxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Bbxx();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.BBID
         *
         * @param bbid the value for tb_bbxx.BBID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bbid(String bbid) {
            obj.setBbid(bbid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.BBMC
         *
         * @param bbmc the value for tb_bbxx.BBMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bbmc(String bbmc) {
            obj.setBbmc(bbmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.BBTB
         *
         * @param bbtb the value for tb_bbxx.BBTB
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bbtb(String bbtb) {
            obj.setBbtb(bbtb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.BBMS
         *
         * @param bbms the value for tb_bbxx.BBMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bbms(String bbms) {
            obj.setBbms(bbms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.BBPT
         *
         * @param bbpt the value for tb_bbxx.BBPT
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bbpt(String bbpt) {
            obj.setBbpt(bbpt);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.BBBH
         *
         * @param bbbh the value for tb_bbxx.BBBH
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bbbh(Integer bbbh) {
            obj.setBbbh(bbbh);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.AZBMC
         *
         * @param azbmc the value for tb_bbxx.AZBMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder azbmc(String azbmc) {
            obj.setAzbmc(azbmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.BBDZ
         *
         * @param bbdz the value for tb_bbxx.BBDZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bbdz(String bbdz) {
            obj.setBbdz(bbdz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.FBSJ
         *
         * @param fbsj the value for tb_bbxx.FBSJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fbsj(String fbsj) {
            obj.setFbsj(fbsj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.QZGX
         *
         * @param qzgx the value for tb_bbxx.QZGX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzgx(String qzgx) {
            obj.setQzgx(qzgx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.XZCS
         *
         * @param xzcs the value for tb_bbxx.XZCS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder xzcs(Integer xzcs) {
            obj.setXzcs(xzcs);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_bbxx.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_bbxx.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.CREATE_TIME
         *
         * @param createTime the value for tb_bbxx.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.CREATE_ID
         *
         * @param createId the value for tb_bbxx.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.UPDATE_TIME
         *
         * @param updateTime the value for tb_bbxx.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_bbxx.UPDATE_ID
         *
         * @param updateId the value for tb_bbxx.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_bbxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Bbxx build() {
            return this.obj;
        }
    }
}