package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_fjxx
 * @Data 2017-12-28
 * @Author chanin 
 * 附件基本信息
 */
public class Fjxx extends BasicObject implements Serializable {
    // 附件主键 (主健ID)
    private String fjid;

    // 附件名称(必填项)
    private String fjmc;

    // 附件描述(可选项)
    private String fjms;

    // 附件类型：图片、视频、文件(必填项)
    private String fjlx;

    // 附件地址(必填项)
    private String fjdz;

    // 服务标签(可选项)
    private String fwbq;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getFjid() {
        return fjid;
    }

    public void setFjid(String fjid) {
        this.fjid = fjid == null ? null : fjid.trim();
    }

    public String getFjmc() {
        return fjmc;
    }

    public void setFjmc(String fjmc) {
        this.fjmc = fjmc == null ? null : fjmc.trim();
    }

    public String getFjms() {
        return fjms;
    }

    public void setFjms(String fjms) {
        this.fjms = fjms == null ? null : fjms.trim();
    }

    public String getFjlx() {
        return fjlx;
    }

    public void setFjlx(String fjlx) {
        this.fjlx = fjlx == null ? null : fjlx.trim();
    }

    public String getFjdz() {
        return fjdz;
    }

    public void setFjdz(String fjdz) {
        this.fjdz = fjdz == null ? null : fjdz.trim();
    }

    public String getFwbq() {
        return fwbq;
    }

    public void setFwbq(String fwbq) {
        this.fwbq = fwbq == null ? null : fwbq.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fjxx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Fjxx.Builder builder() {
        return new Fjxx.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fjid=").append(fjid);
        sb.append(", fjmc=").append(fjmc);
        sb.append(", fjms=").append(fjms);
        sb.append(", fjlx=").append(fjlx);
        sb.append(", fjdz=").append(fjdz);
        sb.append(", fwbq=").append(fwbq);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Fjxx other = (Fjxx) that;
        return (this.getFjid() == null ? other.getFjid() == null : this.getFjid().equals(other.getFjid()))
            && (this.getFjmc() == null ? other.getFjmc() == null : this.getFjmc().equals(other.getFjmc()))
            && (this.getFjms() == null ? other.getFjms() == null : this.getFjms().equals(other.getFjms()))
            && (this.getFjlx() == null ? other.getFjlx() == null : this.getFjlx().equals(other.getFjlx()))
            && (this.getFjdz() == null ? other.getFjdz() == null : this.getFjdz().equals(other.getFjdz()))
            && (this.getFwbq() == null ? other.getFwbq() == null : this.getFwbq().equals(other.getFwbq()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFjid() == null) ? 0 : getFjid().hashCode());
        result = prime * result + ((getFjmc() == null) ? 0 : getFjmc().hashCode());
        result = prime * result + ((getFjms() == null) ? 0 : getFjms().hashCode());
        result = prime * result + ((getFjlx() == null) ? 0 : getFjlx().hashCode());
        result = prime * result + ((getFjdz() == null) ? 0 : getFjdz().hashCode());
        result = prime * result + ((getFwbq() == null) ? 0 : getFwbq().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_fjxx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_fjxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Fjxx obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_fjxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Fjxx();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.FJID
         *
         * @param fjid the value for tb_fjxx.FJID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjid(String fjid) {
            obj.setFjid(fjid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.FJMC
         *
         * @param fjmc the value for tb_fjxx.FJMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjmc(String fjmc) {
            obj.setFjmc(fjmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.FJMS
         *
         * @param fjms the value for tb_fjxx.FJMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjms(String fjms) {
            obj.setFjms(fjms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.FJLX
         *
         * @param fjlx the value for tb_fjxx.FJLX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjlx(String fjlx) {
            obj.setFjlx(fjlx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.FJDZ
         *
         * @param fjdz the value for tb_fjxx.FJDZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjdz(String fjdz) {
            obj.setFjdz(fjdz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.FWBQ
         *
         * @param fwbq the value for tb_fjxx.FWBQ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fwbq(String fwbq) {
            obj.setFwbq(fwbq);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_fjxx.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_fjxx.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.CREATE_TIME
         *
         * @param createTime the value for tb_fjxx.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.CREATE_ID
         *
         * @param createId the value for tb_fjxx.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.UPDATE_TIME
         *
         * @param updateTime the value for tb_fjxx.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_fjxx.UPDATE_ID
         *
         * @param updateId the value for tb_fjxx.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_fjxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Fjxx build() {
            return this.obj;
        }
    }
}