package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_jsxx
 * @Data 2017-12-28
 * @Author chanin 
 * 角色基本信息
 */
public class Jsxx extends BasicObject implements Serializable {
    // 角色主键 (主健ID)
    private String jsid;

    // 父级角色主键(可选项)
    private String fjjsid;

    // 角色名称(可选项)
    private String jsmc;

    // 角色首拼(可选项)
    private String jssp;

    // 角色描述(可选项)
    private String jsms;

    // 角色排序(必填项)
    private Integer jspx;

    // 角色层级(必填项)
    private Integer jscj;

    // 子集标志：有、无(必填项)
    private String subsetSymbol;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getJsid() {
        return jsid;
    }

    public void setJsid(String jsid) {
        this.jsid = jsid == null ? null : jsid.trim();
    }

    public String getFjjsid() {
        return fjjsid;
    }

    public void setFjjsid(String fjjsid) {
        this.fjjsid = fjjsid == null ? null : fjjsid.trim();
    }

    public String getJsmc() {
        return jsmc;
    }

    public void setJsmc(String jsmc) {
        this.jsmc = jsmc == null ? null : jsmc.trim();
    }

    public String getJssp() {
        return jssp;
    }

    public void setJssp(String jssp) {
        this.jssp = jssp == null ? null : jssp.trim();
    }

    public String getJsms() {
        return jsms;
    }

    public void setJsms(String jsms) {
        this.jsms = jsms == null ? null : jsms.trim();
    }

    public Integer getJspx() {
        return jspx;
    }

    public void setJspx(Integer jspx) {
        this.jspx = jspx;
    }

    public Integer getJscj() {
        return jscj;
    }

    public void setJscj(Integer jscj) {
        this.jscj = jscj;
    }

    public String getSubsetSymbol() {
        return subsetSymbol;
    }

    public void setSubsetSymbol(String subsetSymbol) {
        this.subsetSymbol = subsetSymbol == null ? null : subsetSymbol.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jsxx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Jsxx.Builder builder() {
        return new Jsxx.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jsid=").append(jsid);
        sb.append(", fjjsid=").append(fjjsid);
        sb.append(", jsmc=").append(jsmc);
        sb.append(", jssp=").append(jssp);
        sb.append(", jsms=").append(jsms);
        sb.append(", jspx=").append(jspx);
        sb.append(", jscj=").append(jscj);
        sb.append(", subsetSymbol=").append(subsetSymbol);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Jsxx other = (Jsxx) that;
        return (this.getJsid() == null ? other.getJsid() == null : this.getJsid().equals(other.getJsid()))
            && (this.getFjjsid() == null ? other.getFjjsid() == null : this.getFjjsid().equals(other.getFjjsid()))
            && (this.getJsmc() == null ? other.getJsmc() == null : this.getJsmc().equals(other.getJsmc()))
            && (this.getJssp() == null ? other.getJssp() == null : this.getJssp().equals(other.getJssp()))
            && (this.getJsms() == null ? other.getJsms() == null : this.getJsms().equals(other.getJsms()))
            && (this.getJspx() == null ? other.getJspx() == null : this.getJspx().equals(other.getJspx()))
            && (this.getJscj() == null ? other.getJscj() == null : this.getJscj().equals(other.getJscj()))
            && (this.getSubsetSymbol() == null ? other.getSubsetSymbol() == null : this.getSubsetSymbol().equals(other.getSubsetSymbol()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getJsid() == null) ? 0 : getJsid().hashCode());
        result = prime * result + ((getFjjsid() == null) ? 0 : getFjjsid().hashCode());
        result = prime * result + ((getJsmc() == null) ? 0 : getJsmc().hashCode());
        result = prime * result + ((getJssp() == null) ? 0 : getJssp().hashCode());
        result = prime * result + ((getJsms() == null) ? 0 : getJsms().hashCode());
        result = prime * result + ((getJspx() == null) ? 0 : getJspx().hashCode());
        result = prime * result + ((getJscj() == null) ? 0 : getJscj().hashCode());
        result = prime * result + ((getSubsetSymbol() == null) ? 0 : getSubsetSymbol().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_jsxx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_jsxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Jsxx obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_jsxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Jsxx();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.JSID
         *
         * @param jsid the value for tb_jsxx.JSID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder jsid(String jsid) {
            obj.setJsid(jsid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.FJJSID
         *
         * @param fjjsid the value for tb_jsxx.FJJSID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjjsid(String fjjsid) {
            obj.setFjjsid(fjjsid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.JSMC
         *
         * @param jsmc the value for tb_jsxx.JSMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder jsmc(String jsmc) {
            obj.setJsmc(jsmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.JSSP
         *
         * @param jssp the value for tb_jsxx.JSSP
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder jssp(String jssp) {
            obj.setJssp(jssp);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.JSMS
         *
         * @param jsms the value for tb_jsxx.JSMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder jsms(String jsms) {
            obj.setJsms(jsms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.JSPX
         *
         * @param jspx the value for tb_jsxx.JSPX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder jspx(Integer jspx) {
            obj.setJspx(jspx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.JSCJ
         *
         * @param jscj the value for tb_jsxx.JSCJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder jscj(Integer jscj) {
            obj.setJscj(jscj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.SUBSET_SYMBOL
         *
         * @param subsetSymbol the value for tb_jsxx.SUBSET_SYMBOL
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder subsetSymbol(String subsetSymbol) {
            obj.setSubsetSymbol(subsetSymbol);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_jsxx.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_jsxx.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.CREATE_TIME
         *
         * @param createTime the value for tb_jsxx.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.CREATE_ID
         *
         * @param createId the value for tb_jsxx.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.UPDATE_TIME
         *
         * @param updateTime the value for tb_jsxx.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_jsxx.UPDATE_ID
         *
         * @param updateId the value for tb_jsxx.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_jsxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Jsxx build() {
            return this.obj;
        }
    }
}