package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_mbfz
 * @Data 2017-12-28
 * @Author chanin 
 * 模板分组信息
 */
public class Mbfz extends BasicObject implements Serializable {
    // 模板分组主键 (主健ID)
    private String mbfzid;

    // 父级模板分组主键(可选项)
    private String fjmbfzid;

    // 群主主键(必填项)
    private String yhid;

    // 模板分组名称(必填项)
    private String mbfzmc;

    // 模板分组首拼(必填项)
    private String mbfzsp;

    // 模板分组描述(可选项)
    private String mbfzms;

    // 模板分组层级(必填项)
    private Integer mbfzcj;

    // 模板分组排序(必填项)
    private Integer mbfzpx;

    // 模板分组备注(可选项)
    private String mbfzbz;

    // 子集标志：有、无(必填项)
    private String subsetSymbol;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getMbfzid() {
        return mbfzid;
    }

    public void setMbfzid(String mbfzid) {
        this.mbfzid = mbfzid == null ? null : mbfzid.trim();
    }

    public String getFjmbfzid() {
        return fjmbfzid;
    }

    public void setFjmbfzid(String fjmbfzid) {
        this.fjmbfzid = fjmbfzid == null ? null : fjmbfzid.trim();
    }

    public String getYhid() {
        return yhid;
    }

    public void setYhid(String yhid) {
        this.yhid = yhid == null ? null : yhid.trim();
    }

    public String getMbfzmc() {
        return mbfzmc;
    }

    public void setMbfzmc(String mbfzmc) {
        this.mbfzmc = mbfzmc == null ? null : mbfzmc.trim();
    }

    public String getMbfzsp() {
        return mbfzsp;
    }

    public void setMbfzsp(String mbfzsp) {
        this.mbfzsp = mbfzsp == null ? null : mbfzsp.trim();
    }

    public String getMbfzms() {
        return mbfzms;
    }

    public void setMbfzms(String mbfzms) {
        this.mbfzms = mbfzms == null ? null : mbfzms.trim();
    }

    public Integer getMbfzcj() {
        return mbfzcj;
    }

    public void setMbfzcj(Integer mbfzcj) {
        this.mbfzcj = mbfzcj;
    }

    public Integer getMbfzpx() {
        return mbfzpx;
    }

    public void setMbfzpx(Integer mbfzpx) {
        this.mbfzpx = mbfzpx;
    }

    public String getMbfzbz() {
        return mbfzbz;
    }

    public void setMbfzbz(String mbfzbz) {
        this.mbfzbz = mbfzbz == null ? null : mbfzbz.trim();
    }

    public String getSubsetSymbol() {
        return subsetSymbol;
    }

    public void setSubsetSymbol(String subsetSymbol) {
        this.subsetSymbol = subsetSymbol == null ? null : subsetSymbol.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mbfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Mbfz.Builder builder() {
        return new Mbfz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mbfzid=").append(mbfzid);
        sb.append(", fjmbfzid=").append(fjmbfzid);
        sb.append(", yhid=").append(yhid);
        sb.append(", mbfzmc=").append(mbfzmc);
        sb.append(", mbfzsp=").append(mbfzsp);
        sb.append(", mbfzms=").append(mbfzms);
        sb.append(", mbfzcj=").append(mbfzcj);
        sb.append(", mbfzpx=").append(mbfzpx);
        sb.append(", mbfzbz=").append(mbfzbz);
        sb.append(", subsetSymbol=").append(subsetSymbol);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Mbfz other = (Mbfz) that;
        return (this.getMbfzid() == null ? other.getMbfzid() == null : this.getMbfzid().equals(other.getMbfzid()))
            && (this.getFjmbfzid() == null ? other.getFjmbfzid() == null : this.getFjmbfzid().equals(other.getFjmbfzid()))
            && (this.getYhid() == null ? other.getYhid() == null : this.getYhid().equals(other.getYhid()))
            && (this.getMbfzmc() == null ? other.getMbfzmc() == null : this.getMbfzmc().equals(other.getMbfzmc()))
            && (this.getMbfzsp() == null ? other.getMbfzsp() == null : this.getMbfzsp().equals(other.getMbfzsp()))
            && (this.getMbfzms() == null ? other.getMbfzms() == null : this.getMbfzms().equals(other.getMbfzms()))
            && (this.getMbfzcj() == null ? other.getMbfzcj() == null : this.getMbfzcj().equals(other.getMbfzcj()))
            && (this.getMbfzpx() == null ? other.getMbfzpx() == null : this.getMbfzpx().equals(other.getMbfzpx()))
            && (this.getMbfzbz() == null ? other.getMbfzbz() == null : this.getMbfzbz().equals(other.getMbfzbz()))
            && (this.getSubsetSymbol() == null ? other.getSubsetSymbol() == null : this.getSubsetSymbol().equals(other.getSubsetSymbol()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMbfzid() == null) ? 0 : getMbfzid().hashCode());
        result = prime * result + ((getFjmbfzid() == null) ? 0 : getFjmbfzid().hashCode());
        result = prime * result + ((getYhid() == null) ? 0 : getYhid().hashCode());
        result = prime * result + ((getMbfzmc() == null) ? 0 : getMbfzmc().hashCode());
        result = prime * result + ((getMbfzsp() == null) ? 0 : getMbfzsp().hashCode());
        result = prime * result + ((getMbfzms() == null) ? 0 : getMbfzms().hashCode());
        result = prime * result + ((getMbfzcj() == null) ? 0 : getMbfzcj().hashCode());
        result = prime * result + ((getMbfzpx() == null) ? 0 : getMbfzpx().hashCode());
        result = prime * result + ((getMbfzbz() == null) ? 0 : getMbfzbz().hashCode());
        result = prime * result + ((getSubsetSymbol() == null) ? 0 : getSubsetSymbol().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_mbfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_mbfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Mbfz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_mbfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Mbfz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.MBFZID
         *
         * @param mbfzid the value for tb_mbfz.MBFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mbfzid(String mbfzid) {
            obj.setMbfzid(mbfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.FJMBFZID
         *
         * @param fjmbfzid the value for tb_mbfz.FJMBFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjmbfzid(String fjmbfzid) {
            obj.setFjmbfzid(fjmbfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.YHID
         *
         * @param yhid the value for tb_mbfz.YHID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yhid(String yhid) {
            obj.setYhid(yhid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.MBFZMC
         *
         * @param mbfzmc the value for tb_mbfz.MBFZMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mbfzmc(String mbfzmc) {
            obj.setMbfzmc(mbfzmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.MBFZSP
         *
         * @param mbfzsp the value for tb_mbfz.MBFZSP
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mbfzsp(String mbfzsp) {
            obj.setMbfzsp(mbfzsp);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.MBFZMS
         *
         * @param mbfzms the value for tb_mbfz.MBFZMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mbfzms(String mbfzms) {
            obj.setMbfzms(mbfzms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.MBFZCJ
         *
         * @param mbfzcj the value for tb_mbfz.MBFZCJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mbfzcj(Integer mbfzcj) {
            obj.setMbfzcj(mbfzcj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.MBFZPX
         *
         * @param mbfzpx the value for tb_mbfz.MBFZPX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mbfzpx(Integer mbfzpx) {
            obj.setMbfzpx(mbfzpx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.MBFZBZ
         *
         * @param mbfzbz the value for tb_mbfz.MBFZBZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mbfzbz(String mbfzbz) {
            obj.setMbfzbz(mbfzbz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.SUBSET_SYMBOL
         *
         * @param subsetSymbol the value for tb_mbfz.SUBSET_SYMBOL
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder subsetSymbol(String subsetSymbol) {
            obj.setSubsetSymbol(subsetSymbol);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_mbfz.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_mbfz.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.CREATE_TIME
         *
         * @param createTime the value for tb_mbfz.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.CREATE_ID
         *
         * @param createId the value for tb_mbfz.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.UPDATE_TIME
         *
         * @param updateTime the value for tb_mbfz.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mbfz.UPDATE_ID
         *
         * @param updateId the value for tb_mbfz.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_mbfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Mbfz build() {
            return this.obj;
        }
    }
}