package com.model;

import java.io.Serializable;
import java.util.List;

import com.util.model.BasicObject;

/**
 * @TableName tb_mb_tmfz
 * @Data 2018-01-23
 * @Author chanin 
 * 模板记录条目分组信息
 */
public class MbTmfz extends BasicObject implements Serializable {
    // 条目分组主键 (主健ID)
    private String tmfzid;

    // 模板主键(可选项)
    private String mbid;

    // 父级条目分组主键(可选项)
    private String fjtmfzid;

    // 条目分组名称(必填项)
    private String tmfzmc;

    // 条目分组描述(可选项)
    private String tmfzms;

    // 条目分组备注(可选项)
    private String tmfzbz;

    // 编号(可选项)
    private String bh;

    // 条目分组排序(必填项)
    private Integer tmfzpx;

    // 分组类型（普通、列表）(可选项)
    private String tmfzlx;

    // 子集标志(可选项)
    private String subsetSymbol;

    // 分组层级(可选项)
    private Integer fzcj;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;
    
    
    //------------------------
  	//业务逻辑使用属性
  	//------------------------
    
    private List<MbJltm> mbJltms;//模板记录条目
    private List<MbTmfz> mbTmfzs;//子集模板条目分组

    
    private static final long serialVersionUID = 1L;

    public String getTmfzid() {
        return tmfzid;
    }

    public void setTmfzid(String tmfzid) {
        this.tmfzid = tmfzid == null ? null : tmfzid.trim();
    }

    public String getMbid() {
        return mbid;
    }

    public void setMbid(String mbid) {
        this.mbid = mbid == null ? null : mbid.trim();
    }

    public String getFjtmfzid() {
        return fjtmfzid;
    }

    public void setFjtmfzid(String fjtmfzid) {
        this.fjtmfzid = fjtmfzid == null ? null : fjtmfzid.trim();
    }

    public String getTmfzmc() {
        return tmfzmc;
    }

    public void setTmfzmc(String tmfzmc) {
        this.tmfzmc = tmfzmc == null ? null : tmfzmc.trim();
    }

    public String getTmfzms() {
        return tmfzms;
    }

    public void setTmfzms(String tmfzms) {
        this.tmfzms = tmfzms == null ? null : tmfzms.trim();
    }

    public String getTmfzbz() {
        return tmfzbz;
    }

    public void setTmfzbz(String tmfzbz) {
        this.tmfzbz = tmfzbz == null ? null : tmfzbz.trim();
    }

    public String getBh() {
        return bh;
    }

    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    public Integer getTmfzpx() {
        return tmfzpx;
    }

    public void setTmfzpx(Integer tmfzpx) {
        this.tmfzpx = tmfzpx;
    }

    public String getTmfzlx() {
        return tmfzlx;
    }

    public void setTmfzlx(String tmfzlx) {
        this.tmfzlx = tmfzlx == null ? null : tmfzlx.trim();
    }

    public String getSubsetSymbol() {
        return subsetSymbol;
    }

    public void setSubsetSymbol(String subsetSymbol) {
        this.subsetSymbol = subsetSymbol == null ? null : subsetSymbol.trim();
    }

    public Integer getFzcj() {
        return fzcj;
    }

    public void setFzcj(Integer fzcj) {
        this.fzcj = fzcj;
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mb_tmfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static MbTmfz.Builder builder() {
        return new MbTmfz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tmfzid=").append(tmfzid);
        sb.append(", mbid=").append(mbid);
        sb.append(", fjtmfzid=").append(fjtmfzid);
        sb.append(", tmfzmc=").append(tmfzmc);
        sb.append(", tmfzms=").append(tmfzms);
        sb.append(", tmfzbz=").append(tmfzbz);
        sb.append(", bh=").append(bh);
        sb.append(", tmfzpx=").append(tmfzpx);
        sb.append(", tmfzlx=").append(tmfzlx);
        sb.append(", subsetSymbol=").append(subsetSymbol);
        sb.append(", fzcj=").append(fzcj);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MbTmfz other = (MbTmfz) that;
        return (this.getTmfzid() == null ? other.getTmfzid() == null : this.getTmfzid().equals(other.getTmfzid()))
            && (this.getMbid() == null ? other.getMbid() == null : this.getMbid().equals(other.getMbid()))
            && (this.getFjtmfzid() == null ? other.getFjtmfzid() == null : this.getFjtmfzid().equals(other.getFjtmfzid()))
            && (this.getTmfzmc() == null ? other.getTmfzmc() == null : this.getTmfzmc().equals(other.getTmfzmc()))
            && (this.getTmfzms() == null ? other.getTmfzms() == null : this.getTmfzms().equals(other.getTmfzms()))
            && (this.getTmfzbz() == null ? other.getTmfzbz() == null : this.getTmfzbz().equals(other.getTmfzbz()))
            && (this.getBh() == null ? other.getBh() == null : this.getBh().equals(other.getBh()))
            && (this.getTmfzpx() == null ? other.getTmfzpx() == null : this.getTmfzpx().equals(other.getTmfzpx()))
            && (this.getTmfzlx() == null ? other.getTmfzlx() == null : this.getTmfzlx().equals(other.getTmfzlx()))
            && (this.getSubsetSymbol() == null ? other.getSubsetSymbol() == null : this.getSubsetSymbol().equals(other.getSubsetSymbol()))
            && (this.getFzcj() == null ? other.getFzcj() == null : this.getFzcj().equals(other.getFzcj()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTmfzid() == null) ? 0 : getTmfzid().hashCode());
        result = prime * result + ((getMbid() == null) ? 0 : getMbid().hashCode());
        result = prime * result + ((getFjtmfzid() == null) ? 0 : getFjtmfzid().hashCode());
        result = prime * result + ((getTmfzmc() == null) ? 0 : getTmfzmc().hashCode());
        result = prime * result + ((getTmfzms() == null) ? 0 : getTmfzms().hashCode());
        result = prime * result + ((getTmfzbz() == null) ? 0 : getTmfzbz().hashCode());
        result = prime * result + ((getBh() == null) ? 0 : getBh().hashCode());
        result = prime * result + ((getTmfzpx() == null) ? 0 : getTmfzpx().hashCode());
        result = prime * result + ((getTmfzlx() == null) ? 0 : getTmfzlx().hashCode());
        result = prime * result + ((getSubsetSymbol() == null) ? 0 : getSubsetSymbol().hashCode());
        result = prime * result + ((getFzcj() == null) ? 0 : getFzcj().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_mb_tmfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_mb_tmfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private MbTmfz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_mb_tmfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new MbTmfz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.TMFZID
         *
         * @param tmfzid the value for tb_mb_tmfz.TMFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tmfzid(String tmfzid) {
            obj.setTmfzid(tmfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.MBID
         *
         * @param mbid the value for tb_mb_tmfz.MBID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mbid(String mbid) {
            obj.setMbid(mbid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.FJTMFZID
         *
         * @param fjtmfzid the value for tb_mb_tmfz.FJTMFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjtmfzid(String fjtmfzid) {
            obj.setFjtmfzid(fjtmfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.TMFZMC
         *
         * @param tmfzmc the value for tb_mb_tmfz.TMFZMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tmfzmc(String tmfzmc) {
            obj.setTmfzmc(tmfzmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.TMFZMS
         *
         * @param tmfzms the value for tb_mb_tmfz.TMFZMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tmfzms(String tmfzms) {
            obj.setTmfzms(tmfzms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.TMFZBZ
         *
         * @param tmfzbz the value for tb_mb_tmfz.TMFZBZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tmfzbz(String tmfzbz) {
            obj.setTmfzbz(tmfzbz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.BH
         *
         * @param bh the value for tb_mb_tmfz.BH
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bh(String bh) {
            obj.setBh(bh);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.TMFZPX
         *
         * @param tmfzpx the value for tb_mb_tmfz.TMFZPX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tmfzpx(Integer tmfzpx) {
            obj.setTmfzpx(tmfzpx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.TMFZLX
         *
         * @param tmfzlx the value for tb_mb_tmfz.TMFZLX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder tmfzlx(String tmfzlx) {
            obj.setTmfzlx(tmfzlx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.SUBSET_SYMBOL
         *
         * @param subsetSymbol the value for tb_mb_tmfz.SUBSET_SYMBOL
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder subsetSymbol(String subsetSymbol) {
            obj.setSubsetSymbol(subsetSymbol);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.FZCJ
         *
         * @param fzcj the value for tb_mb_tmfz.FZCJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fzcj(Integer fzcj) {
            obj.setFzcj(fzcj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_mb_tmfz.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_mb_tmfz.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.CREATE_TIME
         *
         * @param createTime the value for tb_mb_tmfz.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.CREATE_ID
         *
         * @param createId the value for tb_mb_tmfz.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.UPDATE_TIME
         *
         * @param updateTime the value for tb_mb_tmfz.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_mb_tmfz.UPDATE_ID
         *
         * @param updateId the value for tb_mb_tmfz.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_mb_tmfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public MbTmfz build() {
            return this.obj;
        }
    }

	public List<MbJltm> getMbJltms() {
		return mbJltms;
	}

	public void setMbJltms(List<MbJltm> mbJltms) {
		this.mbJltms = mbJltms;
	}

	public List<MbTmfz> getMbTmfzs() {
		return mbTmfzs;
	}

	public void setMbTmfzs(List<MbTmfz> mbTmfzs) {
		this.mbTmfzs = mbTmfzs;
	}


}