package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_qxxx
 * @Data 2017-12-28
 * @Author chanin 
 * 权限基本信息
 */
public class Qxxx extends BasicObject implements Serializable {
    // 权限主键 (主健ID)
    private String qxId;

    // 父级权限主键(可选项)
    private String fjqxId;

    // 权限名称(必填项)
    private String qxmc;

    // 权限首拼(必填项)
    private String qxsp;

    // 权限描述(可选项)
    private String qxms;

    // 权限排序(必填项)
    private Integer qxpx;

    // 权限类型：菜单权限、数据权限、群成员权限(必填项)
    private String qxlx;

    // 权限层级(必填项)
    private Integer qxcj;

    // 权限路径(可选项)
    private String qxlj;

    // 权限图标(可选项)
    private String qxtb;

    // 子集标志：有、无(必填项)
    private String subsetSymbol;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getQxId() {
        return qxId;
    }

    public void setQxId(String qxId) {
        this.qxId = qxId == null ? null : qxId.trim();
    }

    public String getFjqxId() {
        return fjqxId;
    }

    public void setFjqxId(String fjqxId) {
        this.fjqxId = fjqxId == null ? null : fjqxId.trim();
    }

    public String getQxmc() {
        return qxmc;
    }

    public void setQxmc(String qxmc) {
        this.qxmc = qxmc == null ? null : qxmc.trim();
    }

    public String getQxsp() {
        return qxsp;
    }

    public void setQxsp(String qxsp) {
        this.qxsp = qxsp == null ? null : qxsp.trim();
    }

    public String getQxms() {
        return qxms;
    }

    public void setQxms(String qxms) {
        this.qxms = qxms == null ? null : qxms.trim();
    }

    public Integer getQxpx() {
        return qxpx;
    }

    public void setQxpx(Integer qxpx) {
        this.qxpx = qxpx;
    }

    public String getQxlx() {
        return qxlx;
    }

    public void setQxlx(String qxlx) {
        this.qxlx = qxlx == null ? null : qxlx.trim();
    }

    public Integer getQxcj() {
        return qxcj;
    }

    public void setQxcj(Integer qxcj) {
        this.qxcj = qxcj;
    }

    public String getQxlj() {
        return qxlj;
    }

    public void setQxlj(String qxlj) {
        this.qxlj = qxlj == null ? null : qxlj.trim();
    }

    public String getQxtb() {
        return qxtb;
    }

    public void setQxtb(String qxtb) {
        this.qxtb = qxtb == null ? null : qxtb.trim();
    }

    public String getSubsetSymbol() {
        return subsetSymbol;
    }

    public void setSubsetSymbol(String subsetSymbol) {
        this.subsetSymbol = subsetSymbol == null ? null : subsetSymbol.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_qxxx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Qxxx.Builder builder() {
        return new Qxxx.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qxId=").append(qxId);
        sb.append(", fjqxId=").append(fjqxId);
        sb.append(", qxmc=").append(qxmc);
        sb.append(", qxsp=").append(qxsp);
        sb.append(", qxms=").append(qxms);
        sb.append(", qxpx=").append(qxpx);
        sb.append(", qxlx=").append(qxlx);
        sb.append(", qxcj=").append(qxcj);
        sb.append(", qxlj=").append(qxlj);
        sb.append(", qxtb=").append(qxtb);
        sb.append(", subsetSymbol=").append(subsetSymbol);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Qxxx other = (Qxxx) that;
        return (this.getQxId() == null ? other.getQxId() == null : this.getQxId().equals(other.getQxId()))
            && (this.getFjqxId() == null ? other.getFjqxId() == null : this.getFjqxId().equals(other.getFjqxId()))
            && (this.getQxmc() == null ? other.getQxmc() == null : this.getQxmc().equals(other.getQxmc()))
            && (this.getQxsp() == null ? other.getQxsp() == null : this.getQxsp().equals(other.getQxsp()))
            && (this.getQxms() == null ? other.getQxms() == null : this.getQxms().equals(other.getQxms()))
            && (this.getQxpx() == null ? other.getQxpx() == null : this.getQxpx().equals(other.getQxpx()))
            && (this.getQxlx() == null ? other.getQxlx() == null : this.getQxlx().equals(other.getQxlx()))
            && (this.getQxcj() == null ? other.getQxcj() == null : this.getQxcj().equals(other.getQxcj()))
            && (this.getQxlj() == null ? other.getQxlj() == null : this.getQxlj().equals(other.getQxlj()))
            && (this.getQxtb() == null ? other.getQxtb() == null : this.getQxtb().equals(other.getQxtb()))
            && (this.getSubsetSymbol() == null ? other.getSubsetSymbol() == null : this.getSubsetSymbol().equals(other.getSubsetSymbol()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getQxId() == null) ? 0 : getQxId().hashCode());
        result = prime * result + ((getFjqxId() == null) ? 0 : getFjqxId().hashCode());
        result = prime * result + ((getQxmc() == null) ? 0 : getQxmc().hashCode());
        result = prime * result + ((getQxsp() == null) ? 0 : getQxsp().hashCode());
        result = prime * result + ((getQxms() == null) ? 0 : getQxms().hashCode());
        result = prime * result + ((getQxpx() == null) ? 0 : getQxpx().hashCode());
        result = prime * result + ((getQxlx() == null) ? 0 : getQxlx().hashCode());
        result = prime * result + ((getQxcj() == null) ? 0 : getQxcj().hashCode());
        result = prime * result + ((getQxlj() == null) ? 0 : getQxlj().hashCode());
        result = prime * result + ((getQxtb() == null) ? 0 : getQxtb().hashCode());
        result = prime * result + ((getSubsetSymbol() == null) ? 0 : getSubsetSymbol().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_qxxx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_qxxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Qxxx obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_qxxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Qxxx();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QX_ID
         *
         * @param qxId the value for tb_qxxx.QX_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxId(String qxId) {
            obj.setQxId(qxId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.FJQX_ID
         *
         * @param fjqxId the value for tb_qxxx.FJQX_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjqxId(String fjqxId) {
            obj.setFjqxId(fjqxId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QXMC
         *
         * @param qxmc the value for tb_qxxx.QXMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxmc(String qxmc) {
            obj.setQxmc(qxmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QXSP
         *
         * @param qxsp the value for tb_qxxx.QXSP
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxsp(String qxsp) {
            obj.setQxsp(qxsp);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QXMS
         *
         * @param qxms the value for tb_qxxx.QXMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxms(String qxms) {
            obj.setQxms(qxms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QXPX
         *
         * @param qxpx the value for tb_qxxx.QXPX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxpx(Integer qxpx) {
            obj.setQxpx(qxpx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QXLX
         *
         * @param qxlx the value for tb_qxxx.QXLX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxlx(String qxlx) {
            obj.setQxlx(qxlx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QXCJ
         *
         * @param qxcj the value for tb_qxxx.QXCJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxcj(Integer qxcj) {
            obj.setQxcj(qxcj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QXLJ
         *
         * @param qxlj the value for tb_qxxx.QXLJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxlj(String qxlj) {
            obj.setQxlj(qxlj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.QXTB
         *
         * @param qxtb the value for tb_qxxx.QXTB
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qxtb(String qxtb) {
            obj.setQxtb(qxtb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.SUBSET_SYMBOL
         *
         * @param subsetSymbol the value for tb_qxxx.SUBSET_SYMBOL
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder subsetSymbol(String subsetSymbol) {
            obj.setSubsetSymbol(subsetSymbol);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_qxxx.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_qxxx.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.CREATE_TIME
         *
         * @param createTime the value for tb_qxxx.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.CREATE_ID
         *
         * @param createId the value for tb_qxxx.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.UPDATE_TIME
         *
         * @param updateTime the value for tb_qxxx.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qxxx.UPDATE_ID
         *
         * @param updateId the value for tb_qxxx.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_qxxx
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Qxxx build() {
            return this.obj;
        }
    }
}