package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_qzfz
 * @Data 2017-12-28
 * @Author chanin 
 * 群组分组信息
 */
public class Qzfz extends BasicObject implements Serializable {
    // 群组分组主键 (主健ID)
    private String qzfzid;

    // 父级群组分组主键(可选项)
    private String fjqzfzid;

    // 群主主键(必填项)
    private String yhid;

    // 群组分组名称(必填项)
    private String qzfzmc;

    // 群组分组首拼(必填项)
    private String qzfzsp;

    // 群组分组描述(可选项)
    private String qzfzms;

    // 群组分组层级(必填项)
    private Integer qzfzcj;

    // 群组分组排序(必填项)
    private Integer qzfzpx;

    // 群组分组备注(可选项)
    private String qzfzbz;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getQzfzid() {
        return qzfzid;
    }

    public void setQzfzid(String qzfzid) {
        this.qzfzid = qzfzid == null ? null : qzfzid.trim();
    }

    public String getFjqzfzid() {
        return fjqzfzid;
    }

    public void setFjqzfzid(String fjqzfzid) {
        this.fjqzfzid = fjqzfzid == null ? null : fjqzfzid.trim();
    }

    public String getYhid() {
        return yhid;
    }

    public void setYhid(String yhid) {
        this.yhid = yhid == null ? null : yhid.trim();
    }

    public String getQzfzmc() {
        return qzfzmc;
    }

    public void setQzfzmc(String qzfzmc) {
        this.qzfzmc = qzfzmc == null ? null : qzfzmc.trim();
    }

    public String getQzfzsp() {
        return qzfzsp;
    }

    public void setQzfzsp(String qzfzsp) {
        this.qzfzsp = qzfzsp == null ? null : qzfzsp.trim();
    }

    public String getQzfzms() {
        return qzfzms;
    }

    public void setQzfzms(String qzfzms) {
        this.qzfzms = qzfzms == null ? null : qzfzms.trim();
    }

    public Integer getQzfzcj() {
        return qzfzcj;
    }

    public void setQzfzcj(Integer qzfzcj) {
        this.qzfzcj = qzfzcj;
    }

    public Integer getQzfzpx() {
        return qzfzpx;
    }

    public void setQzfzpx(Integer qzfzpx) {
        this.qzfzpx = qzfzpx;
    }

    public String getQzfzbz() {
        return qzfzbz;
    }

    public void setQzfzbz(String qzfzbz) {
        this.qzfzbz = qzfzbz == null ? null : qzfzbz.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_qzfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Qzfz.Builder builder() {
        return new Qzfz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qzfzid=").append(qzfzid);
        sb.append(", fjqzfzid=").append(fjqzfzid);
        sb.append(", yhid=").append(yhid);
        sb.append(", qzfzmc=").append(qzfzmc);
        sb.append(", qzfzsp=").append(qzfzsp);
        sb.append(", qzfzms=").append(qzfzms);
        sb.append(", qzfzcj=").append(qzfzcj);
        sb.append(", qzfzpx=").append(qzfzpx);
        sb.append(", qzfzbz=").append(qzfzbz);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Qzfz other = (Qzfz) that;
        return (this.getQzfzid() == null ? other.getQzfzid() == null : this.getQzfzid().equals(other.getQzfzid()))
            && (this.getFjqzfzid() == null ? other.getFjqzfzid() == null : this.getFjqzfzid().equals(other.getFjqzfzid()))
            && (this.getYhid() == null ? other.getYhid() == null : this.getYhid().equals(other.getYhid()))
            && (this.getQzfzmc() == null ? other.getQzfzmc() == null : this.getQzfzmc().equals(other.getQzfzmc()))
            && (this.getQzfzsp() == null ? other.getQzfzsp() == null : this.getQzfzsp().equals(other.getQzfzsp()))
            && (this.getQzfzms() == null ? other.getQzfzms() == null : this.getQzfzms().equals(other.getQzfzms()))
            && (this.getQzfzcj() == null ? other.getQzfzcj() == null : this.getQzfzcj().equals(other.getQzfzcj()))
            && (this.getQzfzpx() == null ? other.getQzfzpx() == null : this.getQzfzpx().equals(other.getQzfzpx()))
            && (this.getQzfzbz() == null ? other.getQzfzbz() == null : this.getQzfzbz().equals(other.getQzfzbz()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getQzfzid() == null) ? 0 : getQzfzid().hashCode());
        result = prime * result + ((getFjqzfzid() == null) ? 0 : getFjqzfzid().hashCode());
        result = prime * result + ((getYhid() == null) ? 0 : getYhid().hashCode());
        result = prime * result + ((getQzfzmc() == null) ? 0 : getQzfzmc().hashCode());
        result = prime * result + ((getQzfzsp() == null) ? 0 : getQzfzsp().hashCode());
        result = prime * result + ((getQzfzms() == null) ? 0 : getQzfzms().hashCode());
        result = prime * result + ((getQzfzcj() == null) ? 0 : getQzfzcj().hashCode());
        result = prime * result + ((getQzfzpx() == null) ? 0 : getQzfzpx().hashCode());
        result = prime * result + ((getQzfzbz() == null) ? 0 : getQzfzbz().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_qzfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_qzfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Qzfz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_qzfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Qzfz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.QZFZID
         *
         * @param qzfzid the value for tb_qzfz.QZFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzfzid(String qzfzid) {
            obj.setQzfzid(qzfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.FJQZFZID
         *
         * @param fjqzfzid the value for tb_qzfz.FJQZFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjqzfzid(String fjqzfzid) {
            obj.setFjqzfzid(fjqzfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.YHID
         *
         * @param yhid the value for tb_qzfz.YHID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yhid(String yhid) {
            obj.setYhid(yhid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.QZFZMC
         *
         * @param qzfzmc the value for tb_qzfz.QZFZMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzfzmc(String qzfzmc) {
            obj.setQzfzmc(qzfzmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.QZFZSP
         *
         * @param qzfzsp the value for tb_qzfz.QZFZSP
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzfzsp(String qzfzsp) {
            obj.setQzfzsp(qzfzsp);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.QZFZMS
         *
         * @param qzfzms the value for tb_qzfz.QZFZMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzfzms(String qzfzms) {
            obj.setQzfzms(qzfzms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.QZFZCJ
         *
         * @param qzfzcj the value for tb_qzfz.QZFZCJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzfzcj(Integer qzfzcj) {
            obj.setQzfzcj(qzfzcj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.QZFZPX
         *
         * @param qzfzpx the value for tb_qzfz.QZFZPX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzfzpx(Integer qzfzpx) {
            obj.setQzfzpx(qzfzpx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.QZFZBZ
         *
         * @param qzfzbz the value for tb_qzfz.QZFZBZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzfzbz(String qzfzbz) {
            obj.setQzfzbz(qzfzbz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_qzfz.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_qzfz.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.CREATE_TIME
         *
         * @param createTime the value for tb_qzfz.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.CREATE_ID
         *
         * @param createId the value for tb_qzfz.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.UPDATE_TIME
         *
         * @param updateTime the value for tb_qzfz.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_qzfz.UPDATE_ID
         *
         * @param updateId the value for tb_qzfz.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_qzfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Qzfz build() {
            return this.obj;
        }
    }
}