package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_rwfz
 * @Data 2017-12-28
 * @Author chanin 
 * 任务分组信息
 */
public class Rwfz extends BasicObject implements Serializable {
    // 任务分组主键 (主健ID)
    private String rwfzid;

    // 父级任务分组主键(可选项)
    private String fjrwfzid;

    // 群主主键(必填项)
    private String yhid;

    // 任务分组名称(必填项)
    private String rwfzmc;

    // 任务分组首拼(必填项)
    private String rwfzsp;

    // 任务分组描述(可选项)
    private String rwfzms;

    // 任务分组层级(必填项)
    private Integer rwfzcj;

    // 任务分组排序(必填项)
    private Integer rwfzpx;

    // 任务分组备注(可选项)
    private String rwfzbz;

    // 子集标志：有、无(必填项)
    private String subsetSymbol;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getRwfzid() {
        return rwfzid;
    }

    public void setRwfzid(String rwfzid) {
        this.rwfzid = rwfzid == null ? null : rwfzid.trim();
    }

    public String getFjrwfzid() {
        return fjrwfzid;
    }

    public void setFjrwfzid(String fjrwfzid) {
        this.fjrwfzid = fjrwfzid == null ? null : fjrwfzid.trim();
    }

    public String getYhid() {
        return yhid;
    }

    public void setYhid(String yhid) {
        this.yhid = yhid == null ? null : yhid.trim();
    }

    public String getRwfzmc() {
        return rwfzmc;
    }

    public void setRwfzmc(String rwfzmc) {
        this.rwfzmc = rwfzmc == null ? null : rwfzmc.trim();
    }

    public String getRwfzsp() {
        return rwfzsp;
    }

    public void setRwfzsp(String rwfzsp) {
        this.rwfzsp = rwfzsp == null ? null : rwfzsp.trim();
    }

    public String getRwfzms() {
        return rwfzms;
    }

    public void setRwfzms(String rwfzms) {
        this.rwfzms = rwfzms == null ? null : rwfzms.trim();
    }

    public Integer getRwfzcj() {
        return rwfzcj;
    }

    public void setRwfzcj(Integer rwfzcj) {
        this.rwfzcj = rwfzcj;
    }

    public Integer getRwfzpx() {
        return rwfzpx;
    }

    public void setRwfzpx(Integer rwfzpx) {
        this.rwfzpx = rwfzpx;
    }

    public String getRwfzbz() {
        return rwfzbz;
    }

    public void setRwfzbz(String rwfzbz) {
        this.rwfzbz = rwfzbz == null ? null : rwfzbz.trim();
    }

    public String getSubsetSymbol() {
        return subsetSymbol;
    }

    public void setSubsetSymbol(String subsetSymbol) {
        this.subsetSymbol = subsetSymbol == null ? null : subsetSymbol.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rwfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Rwfz.Builder builder() {
        return new Rwfz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rwfzid=").append(rwfzid);
        sb.append(", fjrwfzid=").append(fjrwfzid);
        sb.append(", yhid=").append(yhid);
        sb.append(", rwfzmc=").append(rwfzmc);
        sb.append(", rwfzsp=").append(rwfzsp);
        sb.append(", rwfzms=").append(rwfzms);
        sb.append(", rwfzcj=").append(rwfzcj);
        sb.append(", rwfzpx=").append(rwfzpx);
        sb.append(", rwfzbz=").append(rwfzbz);
        sb.append(", subsetSymbol=").append(subsetSymbol);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Rwfz other = (Rwfz) that;
        return (this.getRwfzid() == null ? other.getRwfzid() == null : this.getRwfzid().equals(other.getRwfzid()))
            && (this.getFjrwfzid() == null ? other.getFjrwfzid() == null : this.getFjrwfzid().equals(other.getFjrwfzid()))
            && (this.getYhid() == null ? other.getYhid() == null : this.getYhid().equals(other.getYhid()))
            && (this.getRwfzmc() == null ? other.getRwfzmc() == null : this.getRwfzmc().equals(other.getRwfzmc()))
            && (this.getRwfzsp() == null ? other.getRwfzsp() == null : this.getRwfzsp().equals(other.getRwfzsp()))
            && (this.getRwfzms() == null ? other.getRwfzms() == null : this.getRwfzms().equals(other.getRwfzms()))
            && (this.getRwfzcj() == null ? other.getRwfzcj() == null : this.getRwfzcj().equals(other.getRwfzcj()))
            && (this.getRwfzpx() == null ? other.getRwfzpx() == null : this.getRwfzpx().equals(other.getRwfzpx()))
            && (this.getRwfzbz() == null ? other.getRwfzbz() == null : this.getRwfzbz().equals(other.getRwfzbz()))
            && (this.getSubsetSymbol() == null ? other.getSubsetSymbol() == null : this.getSubsetSymbol().equals(other.getSubsetSymbol()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRwfzid() == null) ? 0 : getRwfzid().hashCode());
        result = prime * result + ((getFjrwfzid() == null) ? 0 : getFjrwfzid().hashCode());
        result = prime * result + ((getYhid() == null) ? 0 : getYhid().hashCode());
        result = prime * result + ((getRwfzmc() == null) ? 0 : getRwfzmc().hashCode());
        result = prime * result + ((getRwfzsp() == null) ? 0 : getRwfzsp().hashCode());
        result = prime * result + ((getRwfzms() == null) ? 0 : getRwfzms().hashCode());
        result = prime * result + ((getRwfzcj() == null) ? 0 : getRwfzcj().hashCode());
        result = prime * result + ((getRwfzpx() == null) ? 0 : getRwfzpx().hashCode());
        result = prime * result + ((getRwfzbz() == null) ? 0 : getRwfzbz().hashCode());
        result = prime * result + ((getSubsetSymbol() == null) ? 0 : getSubsetSymbol().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_rwfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_rwfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Rwfz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_rwfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Rwfz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.RWFZID
         *
         * @param rwfzid the value for tb_rwfz.RWFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder rwfzid(String rwfzid) {
            obj.setRwfzid(rwfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.FJRWFZID
         *
         * @param fjrwfzid the value for tb_rwfz.FJRWFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjrwfzid(String fjrwfzid) {
            obj.setFjrwfzid(fjrwfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.YHID
         *
         * @param yhid the value for tb_rwfz.YHID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yhid(String yhid) {
            obj.setYhid(yhid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.RWFZMC
         *
         * @param rwfzmc the value for tb_rwfz.RWFZMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder rwfzmc(String rwfzmc) {
            obj.setRwfzmc(rwfzmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.RWFZSP
         *
         * @param rwfzsp the value for tb_rwfz.RWFZSP
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder rwfzsp(String rwfzsp) {
            obj.setRwfzsp(rwfzsp);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.RWFZMS
         *
         * @param rwfzms the value for tb_rwfz.RWFZMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder rwfzms(String rwfzms) {
            obj.setRwfzms(rwfzms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.RWFZCJ
         *
         * @param rwfzcj the value for tb_rwfz.RWFZCJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder rwfzcj(Integer rwfzcj) {
            obj.setRwfzcj(rwfzcj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.RWFZPX
         *
         * @param rwfzpx the value for tb_rwfz.RWFZPX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder rwfzpx(Integer rwfzpx) {
            obj.setRwfzpx(rwfzpx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.RWFZBZ
         *
         * @param rwfzbz the value for tb_rwfz.RWFZBZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder rwfzbz(String rwfzbz) {
            obj.setRwfzbz(rwfzbz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.SUBSET_SYMBOL
         *
         * @param subsetSymbol the value for tb_rwfz.SUBSET_SYMBOL
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder subsetSymbol(String subsetSymbol) {
            obj.setSubsetSymbol(subsetSymbol);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_rwfz.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_rwfz.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.CREATE_TIME
         *
         * @param createTime the value for tb_rwfz.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.CREATE_ID
         *
         * @param createId the value for tb_rwfz.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.UPDATE_TIME
         *
         * @param updateTime the value for tb_rwfz.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_rwfz.UPDATE_ID
         *
         * @param updateId the value for tb_rwfz.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_rwfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Rwfz build() {
            return this.obj;
        }
    }
}