package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_sjcz_rz
 * @Data 2017-12-28
 * @Author chanin 
 * 数据操作日志
 */
public class SjczRz extends BasicObject implements Serializable {
    // 主键 (主健ID)
    private String id;

    // 操作用户ID(必填项)
    private String yhid;

    // 操作类型：新增、删除、修改、查看(必填项)
    private String czLx;

    // 操作模块(必填项)
    private String czMk;

    // 数据类型(必填项)
    private String sjLx;

    // 操作时间(必填项)
    private String czsj;

    // 操作数据(必填项)
    private String czSj;

    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getYhid() {
        return yhid;
    }

    public void setYhid(String yhid) {
        this.yhid = yhid == null ? null : yhid.trim();
    }

    public String getCzLx() {
        return czLx;
    }

    public void setCzLx(String czLx) {
        this.czLx = czLx == null ? null : czLx.trim();
    }

    public String getCzMk() {
        return czMk;
    }

    public void setCzMk(String czMk) {
        this.czMk = czMk == null ? null : czMk.trim();
    }

    public String getSjLx() {
        return sjLx;
    }

    public void setSjLx(String sjLx) {
        this.sjLx = sjLx == null ? null : sjLx.trim();
    }

    public String getCzsj() {
        return czsj;
    }

    public void setCzsj(String czsj) {
        this.czsj = czsj == null ? null : czsj.trim();
    }

    public String getCzSj() {
        return czSj;
    }

    public void setCzSj(String czSj) {
        this.czSj = czSj == null ? null : czSj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sjcz_rz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static SjczRz.Builder builder() {
        return new SjczRz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", yhid=").append(yhid);
        sb.append(", czLx=").append(czLx);
        sb.append(", czMk=").append(czMk);
        sb.append(", sjLx=").append(sjLx);
        sb.append(", czsj=").append(czsj);
        sb.append(", czSj=").append(czSj);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SjczRz other = (SjczRz) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getYhid() == null ? other.getYhid() == null : this.getYhid().equals(other.getYhid()))
            && (this.getCzLx() == null ? other.getCzLx() == null : this.getCzLx().equals(other.getCzLx()))
            && (this.getCzMk() == null ? other.getCzMk() == null : this.getCzMk().equals(other.getCzMk()))
            && (this.getSjLx() == null ? other.getSjLx() == null : this.getSjLx().equals(other.getSjLx()))
            && (this.getCzsj() == null ? other.getCzsj() == null : this.getCzsj().equals(other.getCzsj()))
            && (this.getCzSj() == null ? other.getCzSj() == null : this.getCzSj().equals(other.getCzSj()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getYhid() == null) ? 0 : getYhid().hashCode());
        result = prime * result + ((getCzLx() == null) ? 0 : getCzLx().hashCode());
        result = prime * result + ((getCzMk() == null) ? 0 : getCzMk().hashCode());
        result = prime * result + ((getSjLx() == null) ? 0 : getSjLx().hashCode());
        result = prime * result + ((getCzsj() == null) ? 0 : getCzsj().hashCode());
        result = prime * result + ((getCzSj() == null) ? 0 : getCzSj().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_sjcz_rz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_sjcz_rz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private SjczRz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_sjcz_rz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new SjczRz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_sjcz_rz.ID
         *
         * @param id the value for tb_sjcz_rz.ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(String id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_sjcz_rz.YHID
         *
         * @param yhid the value for tb_sjcz_rz.YHID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yhid(String yhid) {
            obj.setYhid(yhid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_sjcz_rz.CZ_LX
         *
         * @param czLx the value for tb_sjcz_rz.CZ_LX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder czLx(String czLx) {
            obj.setCzLx(czLx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_sjcz_rz.CZ_MK
         *
         * @param czMk the value for tb_sjcz_rz.CZ_MK
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder czMk(String czMk) {
            obj.setCzMk(czMk);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_sjcz_rz.SJ_LX
         *
         * @param sjLx the value for tb_sjcz_rz.SJ_LX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder sjLx(String sjLx) {
            obj.setSjLx(sjLx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_sjcz_rz.CZSJ
         *
         * @param czsj the value for tb_sjcz_rz.CZSJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder czsj(String czsj) {
            obj.setCzsj(czsj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_sjcz_rz.CZ_SJ
         *
         * @param czSj the value for tb_sjcz_rz.CZ_SJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder czSj(String czSj) {
            obj.setCzSj(czSj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_sjcz_rz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public SjczRz build() {
            return this.obj;
        }
    }
}