package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_stfz
 * @Data 2017-12-28
 * @Author chanin 
 * 实体分组信息
 */
public class Stfz extends BasicObject implements Serializable {
    // 实体分组主键 (主健ID)
    private String stfzid;

    // 父级实体分组主键(可选项)
    private String fjstfzid;

    // 群主主键(必填项)
    private String yhid;

    // 实体分组名称(必填项)
    private String stfzmc;

    // 实体分组首拼(必填项)
    private String stfzsp;

    // 实体分组描述(可选项)
    private String stfzms;

    // 实体分组层级(必填项)
    private Integer stfzcj;

    // 实体分组排序(必填项)
    private Integer stfzpx;

    // 实体分组备注(可选项)
    private String stfzbz;

    // 子集标志：有、无(必填项)
    private String subsetSymbol;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getStfzid() {
        return stfzid;
    }

    public void setStfzid(String stfzid) {
        this.stfzid = stfzid == null ? null : stfzid.trim();
    }

    public String getFjstfzid() {
        return fjstfzid;
    }

    public void setFjstfzid(String fjstfzid) {
        this.fjstfzid = fjstfzid == null ? null : fjstfzid.trim();
    }

    public String getYhid() {
        return yhid;
    }

    public void setYhid(String yhid) {
        this.yhid = yhid == null ? null : yhid.trim();
    }

    public String getStfzmc() {
        return stfzmc;
    }

    public void setStfzmc(String stfzmc) {
        this.stfzmc = stfzmc == null ? null : stfzmc.trim();
    }

    public String getStfzsp() {
        return stfzsp;
    }

    public void setStfzsp(String stfzsp) {
        this.stfzsp = stfzsp == null ? null : stfzsp.trim();
    }

    public String getStfzms() {
        return stfzms;
    }

    public void setStfzms(String stfzms) {
        this.stfzms = stfzms == null ? null : stfzms.trim();
    }

    public Integer getStfzcj() {
        return stfzcj;
    }

    public void setStfzcj(Integer stfzcj) {
        this.stfzcj = stfzcj;
    }

    public Integer getStfzpx() {
        return stfzpx;
    }

    public void setStfzpx(Integer stfzpx) {
        this.stfzpx = stfzpx;
    }

    public String getStfzbz() {
        return stfzbz;
    }

    public void setStfzbz(String stfzbz) {
        this.stfzbz = stfzbz == null ? null : stfzbz.trim();
    }

    public String getSubsetSymbol() {
        return subsetSymbol;
    }

    public void setSubsetSymbol(String subsetSymbol) {
        this.subsetSymbol = subsetSymbol == null ? null : subsetSymbol.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Stfz.Builder builder() {
        return new Stfz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stfzid=").append(stfzid);
        sb.append(", fjstfzid=").append(fjstfzid);
        sb.append(", yhid=").append(yhid);
        sb.append(", stfzmc=").append(stfzmc);
        sb.append(", stfzsp=").append(stfzsp);
        sb.append(", stfzms=").append(stfzms);
        sb.append(", stfzcj=").append(stfzcj);
        sb.append(", stfzpx=").append(stfzpx);
        sb.append(", stfzbz=").append(stfzbz);
        sb.append(", subsetSymbol=").append(subsetSymbol);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Stfz other = (Stfz) that;
        return (this.getStfzid() == null ? other.getStfzid() == null : this.getStfzid().equals(other.getStfzid()))
            && (this.getFjstfzid() == null ? other.getFjstfzid() == null : this.getFjstfzid().equals(other.getFjstfzid()))
            && (this.getYhid() == null ? other.getYhid() == null : this.getYhid().equals(other.getYhid()))
            && (this.getStfzmc() == null ? other.getStfzmc() == null : this.getStfzmc().equals(other.getStfzmc()))
            && (this.getStfzsp() == null ? other.getStfzsp() == null : this.getStfzsp().equals(other.getStfzsp()))
            && (this.getStfzms() == null ? other.getStfzms() == null : this.getStfzms().equals(other.getStfzms()))
            && (this.getStfzcj() == null ? other.getStfzcj() == null : this.getStfzcj().equals(other.getStfzcj()))
            && (this.getStfzpx() == null ? other.getStfzpx() == null : this.getStfzpx().equals(other.getStfzpx()))
            && (this.getStfzbz() == null ? other.getStfzbz() == null : this.getStfzbz().equals(other.getStfzbz()))
            && (this.getSubsetSymbol() == null ? other.getSubsetSymbol() == null : this.getSubsetSymbol().equals(other.getSubsetSymbol()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStfzid() == null) ? 0 : getStfzid().hashCode());
        result = prime * result + ((getFjstfzid() == null) ? 0 : getFjstfzid().hashCode());
        result = prime * result + ((getYhid() == null) ? 0 : getYhid().hashCode());
        result = prime * result + ((getStfzmc() == null) ? 0 : getStfzmc().hashCode());
        result = prime * result + ((getStfzsp() == null) ? 0 : getStfzsp().hashCode());
        result = prime * result + ((getStfzms() == null) ? 0 : getStfzms().hashCode());
        result = prime * result + ((getStfzcj() == null) ? 0 : getStfzcj().hashCode());
        result = prime * result + ((getStfzpx() == null) ? 0 : getStfzpx().hashCode());
        result = prime * result + ((getStfzbz() == null) ? 0 : getStfzbz().hashCode());
        result = prime * result + ((getSubsetSymbol() == null) ? 0 : getSubsetSymbol().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_stfz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_stfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Stfz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_stfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Stfz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.STFZID
         *
         * @param stfzid the value for tb_stfz.STFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder stfzid(String stfzid) {
            obj.setStfzid(stfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.FJSTFZID
         *
         * @param fjstfzid the value for tb_stfz.FJSTFZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fjstfzid(String fjstfzid) {
            obj.setFjstfzid(fjstfzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.YHID
         *
         * @param yhid the value for tb_stfz.YHID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yhid(String yhid) {
            obj.setYhid(yhid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.STFZMC
         *
         * @param stfzmc the value for tb_stfz.STFZMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder stfzmc(String stfzmc) {
            obj.setStfzmc(stfzmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.STFZSP
         *
         * @param stfzsp the value for tb_stfz.STFZSP
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder stfzsp(String stfzsp) {
            obj.setStfzsp(stfzsp);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.STFZMS
         *
         * @param stfzms the value for tb_stfz.STFZMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder stfzms(String stfzms) {
            obj.setStfzms(stfzms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.STFZCJ
         *
         * @param stfzcj the value for tb_stfz.STFZCJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder stfzcj(Integer stfzcj) {
            obj.setStfzcj(stfzcj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.STFZPX
         *
         * @param stfzpx the value for tb_stfz.STFZPX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder stfzpx(Integer stfzpx) {
            obj.setStfzpx(stfzpx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.STFZBZ
         *
         * @param stfzbz the value for tb_stfz.STFZBZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder stfzbz(String stfzbz) {
            obj.setStfzbz(stfzbz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.SUBSET_SYMBOL
         *
         * @param subsetSymbol the value for tb_stfz.SUBSET_SYMBOL
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder subsetSymbol(String subsetSymbol) {
            obj.setSubsetSymbol(subsetSymbol);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_stfz.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_stfz.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.CREATE_TIME
         *
         * @param createTime the value for tb_stfz.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.CREATE_ID
         *
         * @param createId the value for tb_stfz.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.UPDATE_TIME
         *
         * @param updateTime the value for tb_stfz.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_stfz.UPDATE_ID
         *
         * @param updateId the value for tb_stfz.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_stfz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Stfz build() {
            return this.obj;
        }
    }
}