package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_yhdl_rz
 * @Data 2017-12-28
 * @Author chanin 
 * 用户登录日志
 */
public class YhdlRz extends BasicObject implements Serializable {
    // 主键 (主健ID)
    private String id;

    // 登录账号(必填项)
    private String dlzh;

    // 登录平台(必填项)
    private String dlpt;

    // 登录结果(必填项)
    private String dljg;

    // 登录时间(必填项)
    private String dlsj;

    // IP地址(可选项)
    private String ipdz;

    // 客户代理(可选项)
    private String khdl;

    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getDlzh() {
        return dlzh;
    }

    public void setDlzh(String dlzh) {
        this.dlzh = dlzh == null ? null : dlzh.trim();
    }

    public String getDlpt() {
        return dlpt;
    }

    public void setDlpt(String dlpt) {
        this.dlpt = dlpt == null ? null : dlpt.trim();
    }

    public String getDljg() {
        return dljg;
    }

    public void setDljg(String dljg) {
        this.dljg = dljg == null ? null : dljg.trim();
    }

    public String getDlsj() {
        return dlsj;
    }

    public void setDlsj(String dlsj) {
        this.dlsj = dlsj == null ? null : dlsj.trim();
    }

    public String getIpdz() {
        return ipdz;
    }

    public void setIpdz(String ipdz) {
        this.ipdz = ipdz == null ? null : ipdz.trim();
    }

    public String getKhdl() {
        return khdl;
    }

    public void setKhdl(String khdl) {
        this.khdl = khdl == null ? null : khdl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yhdl_rz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static YhdlRz.Builder builder() {
        return new YhdlRz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dlzh=").append(dlzh);
        sb.append(", dlpt=").append(dlpt);
        sb.append(", dljg=").append(dljg);
        sb.append(", dlsj=").append(dlsj);
        sb.append(", ipdz=").append(ipdz);
        sb.append(", khdl=").append(khdl);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YhdlRz other = (YhdlRz) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDlzh() == null ? other.getDlzh() == null : this.getDlzh().equals(other.getDlzh()))
            && (this.getDlpt() == null ? other.getDlpt() == null : this.getDlpt().equals(other.getDlpt()))
            && (this.getDljg() == null ? other.getDljg() == null : this.getDljg().equals(other.getDljg()))
            && (this.getDlsj() == null ? other.getDlsj() == null : this.getDlsj().equals(other.getDlsj()))
            && (this.getIpdz() == null ? other.getIpdz() == null : this.getIpdz().equals(other.getIpdz()))
            && (this.getKhdl() == null ? other.getKhdl() == null : this.getKhdl().equals(other.getKhdl()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDlzh() == null) ? 0 : getDlzh().hashCode());
        result = prime * result + ((getDlpt() == null) ? 0 : getDlpt().hashCode());
        result = prime * result + ((getDljg() == null) ? 0 : getDljg().hashCode());
        result = prime * result + ((getDlsj() == null) ? 0 : getDlsj().hashCode());
        result = prime * result + ((getIpdz() == null) ? 0 : getIpdz().hashCode());
        result = prime * result + ((getKhdl() == null) ? 0 : getKhdl().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_yhdl_rz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yhdl_rz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private YhdlRz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yhdl_rz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new YhdlRz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhdl_rz.ID
         *
         * @param id the value for tb_yhdl_rz.ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(String id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhdl_rz.DLZH
         *
         * @param dlzh the value for tb_yhdl_rz.DLZH
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dlzh(String dlzh) {
            obj.setDlzh(dlzh);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhdl_rz.DLPT
         *
         * @param dlpt the value for tb_yhdl_rz.DLPT
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dlpt(String dlpt) {
            obj.setDlpt(dlpt);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhdl_rz.DLJG
         *
         * @param dljg the value for tb_yhdl_rz.DLJG
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dljg(String dljg) {
            obj.setDljg(dljg);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhdl_rz.DLSJ
         *
         * @param dlsj the value for tb_yhdl_rz.DLSJ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder dlsj(String dlsj) {
            obj.setDlsj(dlsj);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhdl_rz.IPDZ
         *
         * @param ipdz the value for tb_yhdl_rz.IPDZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder ipdz(String ipdz) {
            obj.setIpdz(ipdz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhdl_rz.KHDL
         *
         * @param khdl the value for tb_yhdl_rz.KHDL
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder khdl(String khdl) {
            obj.setKhdl(khdl);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yhdl_rz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public YhdlRz build() {
            return this.obj;
        }
    }
}