package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_yhpz
 * @Data 2017-12-28
 * @Author chanin 
 * 用户配置信息
 */
public class Yhpz extends BasicObject implements Serializable {
    // 配置主键 (主健ID)
    private String pzid;

    // 用户主键(必填项)
    private String yhid;

    // 配置名称(必填项)
    private String pzmc;

    // 配置描述(可选项)
    private String pzms;

    // 配置类型(可选项)
    private String pzlx;

    // 配置内容(可选项)
    private String pznr;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getPzid() {
        return pzid;
    }

    public void setPzid(String pzid) {
        this.pzid = pzid == null ? null : pzid.trim();
    }

    public String getYhid() {
        return yhid;
    }

    public void setYhid(String yhid) {
        this.yhid = yhid == null ? null : yhid.trim();
    }

    public String getPzmc() {
        return pzmc;
    }

    public void setPzmc(String pzmc) {
        this.pzmc = pzmc == null ? null : pzmc.trim();
    }

    public String getPzms() {
        return pzms;
    }

    public void setPzms(String pzms) {
        this.pzms = pzms == null ? null : pzms.trim();
    }

    public String getPzlx() {
        return pzlx;
    }

    public void setPzlx(String pzlx) {
        this.pzlx = pzlx == null ? null : pzlx.trim();
    }

    public String getPznr() {
        return pznr;
    }

    public void setPznr(String pznr) {
        this.pznr = pznr == null ? null : pznr.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yhpz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Yhpz.Builder builder() {
        return new Yhpz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pzid=").append(pzid);
        sb.append(", yhid=").append(yhid);
        sb.append(", pzmc=").append(pzmc);
        sb.append(", pzms=").append(pzms);
        sb.append(", pzlx=").append(pzlx);
        sb.append(", pznr=").append(pznr);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Yhpz other = (Yhpz) that;
        return (this.getPzid() == null ? other.getPzid() == null : this.getPzid().equals(other.getPzid()))
            && (this.getYhid() == null ? other.getYhid() == null : this.getYhid().equals(other.getYhid()))
            && (this.getPzmc() == null ? other.getPzmc() == null : this.getPzmc().equals(other.getPzmc()))
            && (this.getPzms() == null ? other.getPzms() == null : this.getPzms().equals(other.getPzms()))
            && (this.getPzlx() == null ? other.getPzlx() == null : this.getPzlx().equals(other.getPzlx()))
            && (this.getPznr() == null ? other.getPznr() == null : this.getPznr().equals(other.getPznr()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPzid() == null) ? 0 : getPzid().hashCode());
        result = prime * result + ((getYhid() == null) ? 0 : getYhid().hashCode());
        result = prime * result + ((getPzmc() == null) ? 0 : getPzmc().hashCode());
        result = prime * result + ((getPzms() == null) ? 0 : getPzms().hashCode());
        result = prime * result + ((getPzlx() == null) ? 0 : getPzlx().hashCode());
        result = prime * result + ((getPznr() == null) ? 0 : getPznr().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_yhpz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yhpz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Yhpz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yhpz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Yhpz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.PZID
         *
         * @param pzid the value for tb_yhpz.PZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pzid(String pzid) {
            obj.setPzid(pzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.YHID
         *
         * @param yhid the value for tb_yhpz.YHID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yhid(String yhid) {
            obj.setYhid(yhid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.PZMC
         *
         * @param pzmc the value for tb_yhpz.PZMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pzmc(String pzmc) {
            obj.setPzmc(pzmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.PZMS
         *
         * @param pzms the value for tb_yhpz.PZMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pzms(String pzms) {
            obj.setPzms(pzms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.PZLX
         *
         * @param pzlx the value for tb_yhpz.PZLX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pzlx(String pzlx) {
            obj.setPzlx(pzlx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.PZNR
         *
         * @param pznr the value for tb_yhpz.PZNR
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pznr(String pznr) {
            obj.setPznr(pznr);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_yhpz.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_yhpz.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.CREATE_TIME
         *
         * @param createTime the value for tb_yhpz.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.CREATE_ID
         *
         * @param createId the value for tb_yhpz.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.UPDATE_TIME
         *
         * @param updateTime the value for tb_yhpz.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yhpz.UPDATE_ID
         *
         * @param updateId the value for tb_yhpz.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yhpz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Yhpz build() {
            return this.obj;
        }
    }
}