package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_yh_qz
 * @Data 2017-12-28
 * @Author chanin 
 * 用户群组关系信息
 */
public class YhQz extends BasicObject implements Serializable {
    // 群组用户关联主键 (主健ID)
    private String qzYhId;

    // 群组主键(必填项)
    private String qzid;

    // 成员主键(必填项)
    private String yhid;

    // 管理员标志：是、否(必填项)
    private String glybz;

    // 成员角色：群主、一级管理员（修改群信息、修改群任务）、二级管理员（审核、踢出用户）、三级管理员（审核用户）(必填项)
    private String cyjs;
    
    
    // 审核状态
    private String shzt;

    // 审核结果
    private String shjg;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getQzYhId() {
        return qzYhId;
    }

    public void setQzYhId(String qzYhId) {
        this.qzYhId = qzYhId == null ? null : qzYhId.trim();
    }

    public String getQzid() {
        return qzid;
    }

    public void setQzid(String qzid) {
        this.qzid = qzid == null ? null : qzid.trim();
    }

    public String getYhid() {
        return yhid;
    }

    public void setYhid(String yhid) {
        this.yhid = yhid == null ? null : yhid.trim();
    }

    public String getGlybz() {
        return glybz;
    }

    public void setGlybz(String glybz) {
        this.glybz = glybz == null ? null : glybz.trim();
    }

    public String getCyjs() {
        return cyjs;
    }

    public void setCyjs(String cyjs) {
        this.cyjs = cyjs == null ? null : cyjs.trim();
    }

    public String getShzt() {
        return shzt;
    }

    public void setShzt(String shzt) {
        this.shzt = shzt == null ? null : shzt.trim();
    }

    public String getShjg() {
        return shjg;
    }

    public void setShjg(String shjg) {
        this.shjg = shjg == null ? null : shjg.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_YH_QZ
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static YhQz.Builder builder() {
        return new YhQz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qzYhId=").append(qzYhId);
        sb.append(", qzid=").append(qzid);
        sb.append(", yhid=").append(yhid);
        sb.append(", glybz=").append(glybz);
        sb.append(", cyjs=").append(cyjs);
        sb.append(", shzt=").append(shzt);
        sb.append(", shjg=").append(shjg);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YhQz other = (YhQz) that;
        return (this.getQzYhId() == null ? other.getQzYhId() == null : this.getQzYhId().equals(other.getQzYhId()))
            && (this.getQzid() == null ? other.getQzid() == null : this.getQzid().equals(other.getQzid()))
            && (this.getYhid() == null ? other.getYhid() == null : this.getYhid().equals(other.getYhid()))
            && (this.getGlybz() == null ? other.getGlybz() == null : this.getGlybz().equals(other.getGlybz()))
            && (this.getCyjs() == null ? other.getCyjs() == null : this.getCyjs().equals(other.getCyjs()))
            && (this.getShzt() == null ? other.getShzt() == null : this.getShzt().equals(other.getShzt()))
            && (this.getShjg() == null ? other.getShjg() == null : this.getShjg().equals(other.getShjg()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getQzYhId() == null) ? 0 : getQzYhId().hashCode());
        result = prime * result + ((getQzid() == null) ? 0 : getQzid().hashCode());
        result = prime * result + ((getYhid() == null) ? 0 : getYhid().hashCode());
        result = prime * result + ((getGlybz() == null) ? 0 : getGlybz().hashCode());
        result = prime * result + ((getCyjs() == null) ? 0 : getCyjs().hashCode());
        result = prime * result + ((getShzt() == null) ? 0 : getShzt().hashCode());
        result = prime * result + ((getShjg() == null) ? 0 : getShjg().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_YH_QZ
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table TB_YH_QZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private YhQz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table TB_YH_QZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new YhQz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.QZ_YH_ID
         *
         * @param qzYhId the value for TB_YH_QZ.QZ_YH_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzYhId(String qzYhId) {
            obj.setQzYhId(qzYhId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.QZID
         *
         * @param qzid the value for TB_YH_QZ.QZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qzid(String qzid) {
            obj.setQzid(qzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.YHID
         *
         * @param yhid the value for TB_YH_QZ.YHID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yhid(String yhid) {
            obj.setYhid(yhid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.GLYBZ
         *
         * @param glybz the value for TB_YH_QZ.GLYBZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder glybz(String glybz) {
            obj.setGlybz(glybz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.CYJS
         *
         * @param cyjs the value for TB_YH_QZ.CYJS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder cyjs(String cyjs) {
            obj.setCyjs(cyjs);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.SHZT
         *
         * @param shzt the value for TB_YH_QZ.SHZT
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder shzt(String shzt) {
            obj.setShzt(shzt);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.SHJG
         *
         * @param shjg the value for TB_YH_QZ.SHJG
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder shjg(String shjg) {
            obj.setShjg(shjg);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.ENABLE_STATUS
         *
         * @param enableStatus the value for TB_YH_QZ.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.DELETE_STATUS
         *
         * @param deleteStatus the value for TB_YH_QZ.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.CREATE_TIME
         *
         * @param createTime the value for TB_YH_QZ.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.CREATE_ID
         *
         * @param createId the value for TB_YH_QZ.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.UPDATE_TIME
         *
         * @param updateTime the value for TB_YH_QZ.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column TB_YH_QZ.UPDATE_ID
         *
         * @param updateId the value for TB_YH_QZ.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table TB_YH_QZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public YhQz build() {
            return this.obj;
        }
    }
}