package com.model;

import com.util.model.BasicObject;
import java.io.Serializable;

/**
 * @TableName tb_yzgz
 * @Data 2017-12-28
 * @Author chanin 
 * 验证规则
 */
public class Yzgz extends BasicObject implements Serializable {
    // 验证规则主键 (主健ID)
    private String yzgzid;

    // 验证规则类型(可选项)
    private String yzgzlx;

    // 验证规则名称(可选项)
    private String yzgzmc;

    // 验证规则描述(可选项)
    private String yzgzms;

    // 验证规则备注(可选项)
    private String yzgzbz;

    // 验证规则适用类型(可选项)
    private String yzgzsylx;

    // 验证规则内容(必填项)
    private String yzgznr;

    // 启用状态(必填项)
    private String enableStatus;

    // 删除状态(必填项)
    private String deleteStatus;

    // 创建时间(必填项)
    private String createTime;

    // 创建人员(必填项)
    private String createId;

    // 更新时间(必填项)
    private String updateTime;

    // 更新人员(必填项)
    private String updateId;

    private static final long serialVersionUID = 1L;

    public String getYzgzid() {
        return yzgzid;
    }

    public void setYzgzid(String yzgzid) {
        this.yzgzid = yzgzid == null ? null : yzgzid.trim();
    }

    public String getYzgzlx() {
        return yzgzlx;
    }

    public void setYzgzlx(String yzgzlx) {
        this.yzgzlx = yzgzlx == null ? null : yzgzlx.trim();
    }

    public String getYzgzmc() {
        return yzgzmc;
    }

    public void setYzgzmc(String yzgzmc) {
        this.yzgzmc = yzgzmc == null ? null : yzgzmc.trim();
    }

    public String getYzgzms() {
        return yzgzms;
    }

    public void setYzgzms(String yzgzms) {
        this.yzgzms = yzgzms == null ? null : yzgzms.trim();
    }

    public String getYzgzbz() {
        return yzgzbz;
    }

    public void setYzgzbz(String yzgzbz) {
        this.yzgzbz = yzgzbz == null ? null : yzgzbz.trim();
    }

    public String getYzgzsylx() {
        return yzgzsylx;
    }

    public void setYzgzsylx(String yzgzsylx) {
        this.yzgzsylx = yzgzsylx == null ? null : yzgzsylx.trim();
    }

    public String getYzgznr() {
        return yzgznr;
    }

    public void setYzgznr(String yzgznr) {
        this.yzgznr = yzgznr == null ? null : yzgznr.trim();
    }

    public String getEnableStatus() {
        return enableStatus;
    }

    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yzgz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Yzgz.Builder builder() {
        return new Yzgz.Builder();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", yzgzid=").append(yzgzid);
        sb.append(", yzgzlx=").append(yzgzlx);
        sb.append(", yzgzmc=").append(yzgzmc);
        sb.append(", yzgzms=").append(yzgzms);
        sb.append(", yzgzbz=").append(yzgzbz);
        sb.append(", yzgzsylx=").append(yzgzsylx);
        sb.append(", yzgznr=").append(yzgznr);
        sb.append(", enableStatus=").append(enableStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Yzgz other = (Yzgz) that;
        return (this.getYzgzid() == null ? other.getYzgzid() == null : this.getYzgzid().equals(other.getYzgzid()))
            && (this.getYzgzlx() == null ? other.getYzgzlx() == null : this.getYzgzlx().equals(other.getYzgzlx()))
            && (this.getYzgzmc() == null ? other.getYzgzmc() == null : this.getYzgzmc().equals(other.getYzgzmc()))
            && (this.getYzgzms() == null ? other.getYzgzms() == null : this.getYzgzms().equals(other.getYzgzms()))
            && (this.getYzgzbz() == null ? other.getYzgzbz() == null : this.getYzgzbz().equals(other.getYzgzbz()))
            && (this.getYzgzsylx() == null ? other.getYzgzsylx() == null : this.getYzgzsylx().equals(other.getYzgzsylx()))
            && (this.getYzgznr() == null ? other.getYzgznr() == null : this.getYzgznr().equals(other.getYzgznr()))
            && (this.getEnableStatus() == null ? other.getEnableStatus() == null : this.getEnableStatus().equals(other.getEnableStatus()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getYzgzid() == null) ? 0 : getYzgzid().hashCode());
        result = prime * result + ((getYzgzlx() == null) ? 0 : getYzgzlx().hashCode());
        result = prime * result + ((getYzgzmc() == null) ? 0 : getYzgzmc().hashCode());
        result = prime * result + ((getYzgzms() == null) ? 0 : getYzgzms().hashCode());
        result = prime * result + ((getYzgzbz() == null) ? 0 : getYzgzbz().hashCode());
        result = prime * result + ((getYzgzsylx() == null) ? 0 : getYzgzsylx().hashCode());
        result = prime * result + ((getYzgznr() == null) ? 0 : getYzgznr().hashCode());
        result = prime * result + ((getEnableStatus() == null) ? 0 : getEnableStatus().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        return result;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_yzgz
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yzgz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Yzgz obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yzgz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Yzgz();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.YZGZID
         *
         * @param yzgzid the value for tb_yzgz.YZGZID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yzgzid(String yzgzid) {
            obj.setYzgzid(yzgzid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.YZGZLX
         *
         * @param yzgzlx the value for tb_yzgz.YZGZLX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yzgzlx(String yzgzlx) {
            obj.setYzgzlx(yzgzlx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.YZGZMC
         *
         * @param yzgzmc the value for tb_yzgz.YZGZMC
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yzgzmc(String yzgzmc) {
            obj.setYzgzmc(yzgzmc);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.YZGZMS
         *
         * @param yzgzms the value for tb_yzgz.YZGZMS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yzgzms(String yzgzms) {
            obj.setYzgzms(yzgzms);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.YZGZBZ
         *
         * @param yzgzbz the value for tb_yzgz.YZGZBZ
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yzgzbz(String yzgzbz) {
            obj.setYzgzbz(yzgzbz);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.YZGZSYLX
         *
         * @param yzgzsylx the value for tb_yzgz.YZGZSYLX
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yzgzsylx(String yzgzsylx) {
            obj.setYzgzsylx(yzgzsylx);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.YZGZNR
         *
         * @param yzgznr the value for tb_yzgz.YZGZNR
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder yzgznr(String yzgznr) {
            obj.setYzgznr(yzgznr);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.ENABLE_STATUS
         *
         * @param enableStatus the value for tb_yzgz.ENABLE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder enableStatus(String enableStatus) {
            obj.setEnableStatus(enableStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.DELETE_STATUS
         *
         * @param deleteStatus the value for tb_yzgz.DELETE_STATUS
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder deleteStatus(String deleteStatus) {
            obj.setDeleteStatus(deleteStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.CREATE_TIME
         *
         * @param createTime the value for tb_yzgz.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(String createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.CREATE_ID
         *
         * @param createId the value for tb_yzgz.CREATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createId(String createId) {
            obj.setCreateId(createId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.UPDATE_TIME
         *
         * @param updateTime the value for tb_yzgz.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(String updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yzgz.UPDATE_ID
         *
         * @param updateId the value for tb_yzgz.UPDATE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateId(String updateId) {
            obj.setUpdateId(updateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yzgz
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Yzgz build() {
            return this.obj;
        }
    }
}